version: "3.9"

services:
    postgres:
        image: postgres:latest
        platform: linux/amd64
        container_name: my_postgres
        environment:
            POSTGRES_DB: inventoryDB
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: test1234
        ports:
            - "5432:5432"
        networks:
          - acme-nw
    adminer:
        image: ghcr.io/jeliebig/adminer-autologin
        platform: linux/amd64
        environment:
            ADMINER_PLUGINS: login-env-vars
            ADMINER_DRIVER: pgsql
            ADMINER_SERVER: my_postgres
            ADMINER_USERNAME: admin
            ADMINER_PASSWORD: test1234
            ADMINER_DB: inventoryDB
            ADMINER_DESIGN: dracula
        ports:
            - 8081:8080
        networks:
            - acme-nw
    axonserver:
        image: axoniq/axonserver:2024.0.2
        container_name: axonserver
        ports:
            - "9090:9090"    # HTTP port
            - "9091:9091"    # GRPC port
            - "8224:8224"    # Cluster port
        environment:
            - axoniq.axonserver.name=inventory-server
            - server.port=9090                      # Custom HTTP port if needed
            - axoniq.axonserver.port=9091           # Custom GRPC port if needed
            - AXONSERVER_EVENTSTORE=/data/eventstore
            - AXONSERVER_CONTROLDB=/data/controldb
        volumes:
            - axonserver_data:/data
        networks:
            - acme-nw
volumes:
  axonserver_data:

networks:
    acme-nw:
        driver: bridge
